document.addEventListener('DOMContentLoaded', () => {
    // Modal functionality
    const modalBtn = document.getElementById('open-modal-btn');
    const modalOverlay = document.getElementById('modal-overlay');
    const barrelForm = document.getElementById('barrel-form');
    const fileUpload = document.getElementById('file-upload');
    const fileName = document.getElementById('file-name');
    let isSubmitting = false;

    modalBtn.addEventListener('click', () => {
        modalOverlay.style.display = 'flex';
    });

    modalOverlay.addEventListener('click', (e) => {
        if (e.target === modalOverlay) {
            modalOverlay.style.display = 'none';
        }
    });

    fileUpload.addEventListener('change', function() {
        fileName.textContent = this.files.length > 0 ? this.files[0].name : 'No file chosen';
    });

barrelForm.addEventListener('submit', async (e) => {
    e.preventDefault();
    if (isSubmitting) return;
    isSubmitting = true;

    const formData = {
        name: document.getElementById('name').value,
        date: document.getElementById('date').value,
        author: document.getElementById('author').value,
        fileName: fileUpload.files[0]?.name
    };
    console.log('Form data:', formData);
    

    const webhookUrl = 'https://discord.com/api/webhooks/1409558263959126078/KWli6kLyp-riGTcGVVHkmbz4rLP--_PkFqCD4hkok4EujJmX9ssf2b7kv0olBde5tEYE';
    
    try {
        const discordData = new FormData();
        const file = fileUpload.files[0];
        

        if (file) {
            discordData.append('file', file);
        }
        

        discordData.append('payload_json', JSON.stringify({
            content: 'Nowy barrel został dodany! <@1262362827998629908>',
            allowed_mentions: { parse: [], users: ['1262362827998629908'] },
            embeds: [{
                title: '🛢️ Nowe zgłoszenie',
                description: 'Pojawiło się nowe zgłoszenie w BarrelPedii. Sprawdź szczegóły poniżej.',
                color: 0x5B8DEF,
                fields: [
                    { name: 'Nazwa', value: formData.name || 'Brak danych', inline: true },
                    { name: 'Data', value: formData.date || 'Brak danych', inline: true },
                    { name: 'Autor', value: formData.author || 'Brak danych', inline: true },
                    { name: 'Plik', value: file ? file.name : 'Brak pliku' }
                ],
                footer: { text: 'BarrelPedia • Automatyczne zgłoszenie' },
                timestamp: new Date().toISOString()
            }]
        }));

  
        await fetch(webhookUrl, {
            method: 'POST',
            body: discordData
        });

        modalOverlay.style.display = 'none';
        barrelForm.reset();
        fileName.textContent = 'No file chosen';
        
    } catch (error) {
        console.error('Error:', error);

    } finally {
        isSubmitting = false;
    }
});

document.getElementById('file-upload').addEventListener('change', function() {
});


    const notInGameBtn = document.getElementById('not-in-game-btn');
    const inGameBtn = document.getElementById('in-game-btn');
    const barrelImages = document.querySelectorAll('.barrel-image');
    
    let currentFilter = 'in-game';
    

    function filterBarrels(category) {
        barrelImages.forEach(img => {
            if (category === 'all') {
                img.style.display = 'block';
            } else if (img.getAttribute('data-category') === category) {
                img.style.display = 'block';
            } else {
                img.style.display = 'none';
            }
        });
        

        notInGameBtn.classList.remove('active');
        inGameBtn.classList.remove('active');
        
        if (category === 'not-in-game') {
            notInGameBtn.classList.add('active');
        } else if (category === 'in-game') {
            inGameBtn.classList.add('active');
        }
    }
    

    notInGameBtn.addEventListener('click', () => {
        currentFilter = 'not-in-game';
        filterBarrels('not-in-game');
    });
    
    inGameBtn.addEventListener('click', () => {
        currentFilter = 'in-game';
        filterBarrels('in-game');
    });


    filterBarrels('in-game');


    const tooltip = document.getElementById('tooltip');
    const tooltipTitle = document.getElementById('tooltip-title');
    const tooltipDesc1 = document.getElementById('tooltip-desc1');
    const tooltipDesc2 = document.getElementById('tooltip-desc2');

    const barrelData = {
        '203': { title: 'Cyber Milk', desc1: 'Date: ??/??/2018', desc2: 'Author: tnt_times' },
        '204': { title: 'Champion', desc1: 'Date: ??/??/2018', desc2: 'Author: Schrottii' },
        '205': { title: "Edible / Where's the Toast?", desc1: 'Date: ??/??/2018', desc2: 'Author: TheKingofTrash' },
        '208': { title: '3.13 / 3.47 / 4.22', desc1: 'Date: ??/??/2019', desc2: 'Author: Bird' },
        '209': { title: 'T-Virus', desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '210': { title: 'Cloud 9', desc1: 'Date: ??/??/2019', desc2: 'Author: Zockerapfel' },
        '211': { title: 'Havana', desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '212': { title: 'Antidote', desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '213': { title: 'Motorhead', desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '214': { title: 'Peyote', desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '215': { title: 'Sub Zero', desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '216': { title: '180', desc1: 'Date: ??/??/2019', desc2: 'Author: Buck' },
        '217': { title: 'SGBG', desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '218': { title: "Where's the fuse?", desc1: 'Date: ??/??/2019', desc2: 'Author: Buck' },
        '220': { title: 'Cool', desc1: 'Date: ??/??/2019', desc2: 'Author: Buck' },
        '221': { title: 'Happy Birthday, Scrap 2', desc1: 'Date: ??/??/2019', desc2: 'Author: Schrottii' },
        '223': { title: 'Keep Dry', desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '224': { title: 'Cut the Blue Wire...?', desc1: 'Date: ??/??/2019', desc2: 'Author: Buck' },
        '225': { title: 'Shrove', desc1: 'Date: ??/??/2019', desc2: 'Author: Schrottii' },
        '226': { title: 'Pizza Party', desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '227': { title: 'Creme', desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '228': { title: 'No Stamp required / Message in a jar', desc1: 'Date: ??/??/2019', desc2: 'Author: Fern' },
        '229': { title: 'Double Down', desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '230': { title: 'Bit', desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '231': { title: 'Carat', desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '232': { title: 'Slurp!', desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '233': { title: 'Jack and Jill', desc1: 'Date: ??/??/2019', desc2: 'Author: Buck' },
        '234': { title: 'Cow Juice', desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '235': { title: 'Come Fly With Me', desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '236': { title: 'R.I.P.', desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '237': { title: 'Hacker Alert', desc1: 'Date: ??/??/2019', desc2: 'Author: Buck' },
        '238': { title: 'Pentatower', desc1: 'Date: ??/??/2019', desc2: 'Author: NXISE' },
        '239': { title: 'Not Too Hot', desc1: 'Date: ??/??/2019', desc2: 'Author: Bird' },
        '240': { title: 'Not Too Cold', desc1: 'Date: ??/??/2019', desc2: 'Author: NXISE' },
        '241': { title: "Where's the Pepper?", desc1: 'Date: ??/??/2019', desc2: 'Author: NXISE' },
        '242': { title: 'Impossibarrel', desc1: 'Date: ??/??/2019', desc2: 'Author: Bird' },
        '243': { title: 'Ethereal', desc1: 'Date: ??/??/2019', desc2: 'Author: Buck' },
        '244': { title: 'Confusion', desc1: 'Date: ??/??/2019', desc2: 'Author: NXISE' },
        '245': { title: "Where's the Jukebox?", desc1: 'Date: ??/??/2019', desc2: 'Author: Bird' },
        '246': { title: 'Heretic', desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '247': { title: 'S2D2', desc1: 'Date: ??/??/2019', desc2: 'Author: Buck' },
        '248': { title: 'Chamber', desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '249': { title: 'Neon', desc1: 'Date: ??/??/2019', desc2: 'Author: NXISE' },
        '250': { title: 'Do Not Lick', desc1: 'Date: ??/??/2019', desc2: 'Author: Buck' },
        '251': { title: 'Ribbed', desc1: 'Date: ??/??/2019', desc2: 'Author: Schrottii' },
        '252': { title: 'Biscuit vs. Cookie', desc1: 'Date: ??/??/2019', desc2: 'Author: NXISE' },
        '253': { title: 'Ladies Night', desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '254': { title: 'Carbonated', desc1: 'Date: ??/??/2019', desc2: 'Author: Schrottii' },
        '255': { title: 'Eternal Darkness', desc1: 'Date: ??/??/2019', desc2: 'Author: Vepro (remade by ???)' },
        '256': { title: 'Mehiko', desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '257': { title: 'Special Delivery', desc1: 'Date: ??/??/2019', desc2: 'Author: Gegiojon' },
        '258': { title: 'More Pancakes?', desc1: 'Date: ??/??/2019', desc2: 'Author: Gegiojon' },
        '259': { title: 'One Missing', desc1: 'Date: ??/??/2019', desc2: 'Author: Buck' },
        '260': { title: "You've Got Mail", desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '261': { title: "Where's the Needle?", desc1: 'Date: ??/??/2019', desc2: 'Author: Gegiojon' },
        '262': { title: 'Night Fever', desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '263': { title: 'The Cure', desc1: 'Date: ??/??/2019', desc2: 'Author: Buck' },
        '264': { title: 'Barrel (bl) Z264', desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '265': { title: 'Format C', desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '266': { title: '2d(R-r)', desc1: 'Date: ??/??/2019', desc2: 'Author: Gegiojon' },
        '267': { title: 'Malevolence', desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '268': { title: 'All my Love', desc1: 'Date: ??/??/2019', desc2: 'Author: Bird' },
        '269': { title: 'Fodder', desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '270': { title: 'WC Emergency', desc1: 'Date: ??/??/2019', desc2: 'Author: Gegiojon (edited by TheKingofTrash)' },
        '271': { title: 'Bluestacks', desc1: 'Date: ??/??/2019', desc2: 'Author: NXISE' },
        '272': { title: "Five O's", desc1: 'Date: ??/??/2019', desc2: 'Author: Rainbowflame (edited by TheKingofTrash)' },
        '273': { title: 'Tropical Milkshake', desc1: 'Date: ??/??/2019', desc2: 'Author: Gegiojon' },
        '274': { title: "The World Keeps Turnin'", desc1: 'Date: ??/??/2019', desc2: 'Author: Unknown' },
        '275': { title: 'Original Delivery', desc1: 'Date: ??/??/2019', desc2: 'Author: Gegiojon' },
        '276': { title: "Where's the Tequilla?", desc1: 'Date: ??/??/2019', desc2: 'Author: Buck' },
        '277': { title: '16R23L42R', desc1: 'Date: ??/??/2019', desc2: 'Author: Buck' },
        '278': { title: 'Blue Magic', desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '279': { title: 'On or Off?', desc1: 'Date: ??/??/2019', desc2: 'Author: Buck' },
        '280': { title: 'Amazingly Corny', desc1: 'Date: ??/??/2019', desc2: 'Author: Gegiojon' },
        '281': { title: 'A Barrel A Day', desc1: 'Date: ??/??/2019', desc2: 'Author: Bird' },
        '282': { title: 'Open With Care', desc1: 'Date: ??/??/2019', desc2: 'Author: Hiruma' },
        '283': { title: 'The Scrap Chronicles', desc1: 'Date: ??/??/2019', desc2: 'Author: Hiruma' },
        '284': { title: 'Yummy!', desc1: 'Date: ??/??/2019', desc2: 'Author: Buck' },
        '285': { title: 'Baozi', desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '286': { title: 'Tesseract', desc1: 'Date: ??/??/2019', desc2: 'Author: Gegiojon' },
        '287': { title: "Scrap O'clock", desc1: 'Date: ??/??/2019', desc2: 'Author: Buck' },
        '288': { title: 'Rainbow Cake', desc1: 'Date: ??/??/2019', desc2: 'Author: Bird' },
        '289': { title: 'Time to Merge!', desc1: 'Date: ??/??/2019', desc2: 'Author: Gegiojon' },
        '290': { title: 'Top Drawer', desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '291': { title: 'Schrott Bucks', desc1: 'Date: ??/??/2019', desc2: 'Author: Gegiojon' },
        '292': { title: 'Scrapyola', desc1: 'Date: ??/??/2019', desc2: 'Author: Bird' },
        '293': { title: 'Stacked and Sweet', desc1: 'Date: ??/??/2019', desc2: 'Author: Schrottii' },
        '294': { title: 'Use By July 2019', desc1: 'Date: ??/??/2019', desc2: 'Author: Hiruma' },
        '295': { title: 'Got any change?', desc1: 'Date: ??/??/2019', desc2: 'Author: Buck' },
        '296': { title: 'Not The Bird', desc1: 'Date: ??/??/2019', desc2: 'Author: RainbowFlame (edited by Gegiojon & TheKingofTrash)' },
        '297': { title: 'Expertly Sliced', desc1: 'Date: ??/??/2019', desc2: 'Author: Rainbowflame (edited by TheKingofTrash)' },
        '298': { title: '1969', desc1: 'Date: ??/??/2019', desc2: 'Author: Gegiojon' },
        '299': { title: 'Do Not Drop', desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '300': { title: 'Barrel 300!', desc1: 'Date: ??/??/2019', desc2: 'Author: Schrottii' },
        '301': { title: 'Face to face', desc1: 'Date: ??/??/2019', desc2: 'Author: Bird' },
        '302': { title: 'Nude Wristwatch', desc1: 'Date: ??/??/2019', desc2: 'Author: Buck' },
        '303': { title: 'My Documents', desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '304': { title: 'Quick to the Point', desc1: 'Date: ??/??/2019', desc2: 'Author: Imbamover (edited by Buck)' },
        '305': { title: 'Lavender scented', desc1: 'Date: ??/??/2019', desc2: 'Author: Bird' },
        '306': { title: 'Merger sponge', desc1: 'Date: ??/??/2019', desc2: 'Author: Bird' },
        '307': { title: 'To the moon!', desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '308': { title: "Where's the lamb sauce?!", desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '309': { title: "Where's that orange cat?", desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '310': { title: 'Torque', desc1: 'Date: ??/??/2019', desc2: 'Author: Bird' },
        '312': { title: 'From the Hangar', desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '313': { title: 'Washing Machine', desc1: 'Date: ??/??/2019', desc2: 'Author: Buck' },
        '314': { title: 'Penne al tonno', desc1: 'Date: ??/??/2019', desc2: 'Author: Unknown' },
        '315': { title: "Where's the Mayonnaise?", desc1: 'Date: ??/??/2019', desc2: 'Author: Unknown' },
        '316': { title: 'Ready to eat', desc1: 'Date: ??/??/2019', desc2: 'Author: ThomasBn' },
        '317': { title: 'Delicious', desc1: 'Date: ??/??/2019', desc2: 'Author: Unknown' },
        '318': { title: 'KiBa', desc1: 'Date: ??/??/2019', desc2: 'Author: Unknown' },
        '319': { title: 'Deliciously Baked', desc1: 'Date: ??/??/2019', desc2: 'Author: Unknown' },
        '320': { title: 'Childhood', desc1: 'Date: ??/??/2019', desc2: 'Author: Bird' },
        '321': { title: 'Cuppa Joe', desc1: 'Date: ??/??/2019', desc2: 'Author: jonfunk' },
        '322': { title: 'Gotcha!', desc1: 'Date: ??/??/2019', desc2: 'Author: Buck' },
        '323': { title: 'Past and Present', desc1: 'Date: ??/??/2019', desc2: 'Author: Buck' },
        '324': { title: 'Chain Reaction', desc1: 'Date: ??/??/2019', desc2: 'Author: Bird' },
        '325': { title: 'Merge like an Egyptian', desc1: 'Date: ??/??/2019', desc2: 'Author: Hiruma' },
        '326': { title: 'Heating up!', desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '327': { title: 'How to Eat?!', desc1: 'Date: ??/??/2019', desc2: 'Author: Rainbowflame (edited by TheKingofTrash)' },
        '328': { title: 'Shake it', desc1: 'Date: ??/??/2019', desc2: 'Author: Hiruma' },
        '329': { title: "Where's the Hotdog?", desc1: 'Date: ??/??/2019', desc2: 'Author: Unknown' },
        '330': { title: 'DING!', desc1: 'Date: ??/??/2019', desc2: 'Author: Unknown' },
        '331': { title: 'Duck Soup', desc1: 'Date: ??/??/2019', desc2: 'Author: Unknown' },
        '332': { title: 'Any Which Way But...', desc1: 'Date: ??/??/2019', desc2: 'Author: Imbamover' },
        '333': { title: 'Sane Frog', desc1: 'Date: ??/??/2019', desc2: 'Author: Mirtle' },
        '334': { title: 'A stitch in time...', desc1: 'Date: ??/??/2019', desc2: 'Author: Bird' },
        '335': { title: 'Scream!', desc1: 'Date: ??/??/2019', desc2: 'Author: Hiruma' },
        '336': { title: 'Déjà Vu', desc1: 'Date: ??/??/2019', desc2: 'Author: Unknown' },
        '337': { title: "Where's the Butter?", desc1: 'Date: ??/??/2019', desc2: 'Author: Unknown' },
        '338': { title: 'A Cold Reception', desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '339': { title: 'Listen Please', desc1: 'Date: ??/??/2019', desc2: 'Author: Hiruma' },
        '340': { title: 'Ninja', desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '341': { title: 'Tired', desc1: 'Date: ??/??/2019', desc2: 'Author: Unknown' },
        '342': { title: "Don't touch Anything", desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '343': { title: 'Chicken or Duck?', desc1: 'Date: ??/??/2019', desc2: 'Author: ThomasBn' },
        '344': { title: 'C12H12', desc1: 'Date: ??/??/2019', desc2: 'Author: Buck' },
        '345': { title: 'Surprise Box', desc1: 'Date: ??/??/2019', desc2: 'Author: TheKingofTrash' },
        '346': { title: 'Where is my burger?', desc1: 'Date: ??/??/2019', desc2: 'Author: Unknown' },
        '347': { title: 'Backyard', desc1: 'Date: ??/??/2019', desc2: 'Author: Gegiojon' },
        '348': { title: 'Hair Bane', desc1: 'Date: ??/??/2019', desc2: 'Author: Bird' },
        '349': { title: 'Scrapels', desc1: 'Date: ??/??/2020', desc2: 'Author: Unknown' },
        '350': { title: "What's cookin'?", desc1: 'Date: ??/??/2020', desc2: 'Author: Unknown' },
        '351': { title: "Don't Feed the Dev / Duck food", desc1: 'Date: ??/??/2020', desc2: 'Author: Unknown' },
        '352': { title: 'Gravity', desc1: 'Date: ??/??/2020', desc2: 'Author: Hiruma' },
        '353': { title: 'Light & Darkness', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '354': { title: 'Skyscraper', desc1: 'Date: ??/??/2020', desc2: 'Author: Unknown' },
        '355': { title: 'Hot & Spicy', desc1: 'Date: ??/??/2020', desc2: 'Author: Unknown' },
        '356': { title: 'Mr. Robot', desc1: 'Date: ??/??/2020', desc2: 'Author: Buck' },
        '357': { title: 'Steamed Ham', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '358': { title: 'How to become rich', desc1: 'Date: ??/??/2020', desc2: 'Author: Hiruma' },
        '359': { title: 'Reverse', desc1: 'Date: ??/??/2020', desc2: 'Author: Unknown' },
        '360': { title: 'Next Dimension', desc1: 'Date: ??/??/2020', desc2: 'Author: Hiruma' },
        '361': { title: 'Masterchef', desc1: 'Date: ??/??/2020', desc2: 'Author: Unknown' },
        '362': { title: 'Guess the word', desc1: 'Date: ??/??/2020', desc2: 'Author: Buck' },
        '363': { title: 'Fixit', desc1: 'Date: ??/??/2020', desc2: 'Author: Buck' },
        '364': { title: "Where's the Bunny?", desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '365': { title: '147', desc1: 'Date: ??/??/2020', desc2: 'Author: Buck' },
        '366': { title: 'Out of stock', desc1: 'Date: ??/??/2020', desc2: 'Author: Unknown' },
        '367': { title: 'Quackuccino', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '368': { title: 'Colony Drop', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '369': { title: 'Heal up!', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '370': { title: 'Satellite 15', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '371': { title: 'Breathe Deep', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '372': { title: 'Solid State', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '373': { title: 'A barrel companion', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '374': { title: 'Home Sweet Home', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '375': { title: 'Pick your favorite!', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '376': { title: 'Two by two', desc1: 'Date: ??/??/2020', desc2: 'Author: Fern (fully finished by TheKingofTrash)' },
        '377': { title: 'Get in the tank!', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '378': { title: 'Checkmate!', desc1: 'Date: ??/??/2020', desc2: 'Author: Hiruma' },
        '379': { title: '1000°', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '380': { title: 'Oh snap!', desc1: 'Date: ??/??/2020', desc2: 'Author: Aloee (remade by TheKingofTrash)' },
        '381': { title: 'Hole in one', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '382': { title: 'Noodles', desc1: 'Date: ??/??/2020', desc2: 'Author: Unknown' },
        '383': { title: 'Not an instrument', desc1: 'Date: ??/??/2020', desc2: 'Author: Unknown' },
        '384': { title: 'Nice Ice', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '385': { title: 'Glug, glug, belch', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '386': { title: "What's playing?", desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '387': { title: '7.0', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '388': { title: 'Bitter citrus', desc1: 'Date: ??/??/2020', desc2: 'Author: Gegiojon' },
        '389': { title: 'Plug in here', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '390': { title: 'Sorbet', desc1: 'Date: ??/??/2020', desc2: 'Author: Masteryman (remade by TheKingofTrash)' },
        '391': { title: 'Take a Break', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '392': { title: 'Bracer of Nobility', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '393': { title: 'Vitamin Bomb', desc1: 'Date: ??/??/2020', desc2: 'Author: Hiruma' },
        '394': { title: 'So tasty', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '395': { title: 'ACGT', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '396': { title: 'Roses and hearts', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '397': { title: 'Where are the knights?', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '398': { title: 'Scrappy Condo', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '399': { title: 'Stop... Merging time!', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '400': { title: 'Congratulations!', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '401': { title: 'Throw a coin', desc1: 'Date: ??/??/2020', desc2: 'Author: Schrottii' },
        '402': { title: 'Off-brand', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '403': { title: 'Bubble Tea', desc1: 'Date: ??/??/2020', desc2: 'Author: Buck' },
        '404': { title: 'From the Freezer', desc1: 'Date: ??/??/2020', desc2: 'Author: Zockerapfel (remade by TheKingofTrash)' },
        '405': { title: "Where's Jelly?", desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '406': { title: 'The whole history', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '407': { title: 'The code is 0000', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '408': { title: '50 Hz', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '409': { title: 'Target Acquired', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '410': { title: "Where's the Blueberry?", desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '411': { title: 'Theoretical Space Line', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '412': { title: 'Vitamin D', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '413': { title: "Where's the Billiard?", desc1: 'Date: ??/??/2020', desc2: 'Author: Buck' },
        '414': { title: 'Would you drink this?', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '415': { title: 'Ultimate Energy', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '416': { title: "Smoker's Paradise", desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '417': { title: 'Shrove 3.0', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '418': { title: 'Please help me', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '419': { title: 'What What in the Button', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '420': { title: "Today's Food", desc1: 'Date: ??/??/2020', desc2: 'Author: Schrottii' },
        '421': { title: 'The Vintage Keeper', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '422': { title: 'Chocolate Dream', desc1: 'Date: ??/??/2020', desc2: 'Author: Schrottii (remade by Hiruma)' },
        '423': { title: 'Bavaria', desc1: 'Date: ??/??/2020', desc2: 'Author: Schrottii' },
        '424': { title: 'Yule Bear', desc1: 'Date: ??/??/2020', desc2: 'Author: Thyme' },
        '425': { title: 'Pshoom!', desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '426': { title: "Where's Boggy?", desc1: 'Date: ??/??/2020', desc2: 'Author: TheKingofTrash' },
        '427': { title: "Something's brewing", desc1: 'Date: ??/??/2021', desc2: 'Author: Bird' },
        '428': { title: 'Points of view', desc1: 'Date: ??/??/2021', desc2: 'Author: Bird' },
        '429': { title: 'Stack of Vitamins', desc1: 'Date: ??/??/2021', desc2: 'Author: Wow' },
        '430': { title: 'Blaze it!', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '431': { title: 'Paisley', desc1: 'Date: ??/??/2021', desc2: 'Author: Bird' },
        '432': { title: 'Wrong lever', desc1: 'Date: ??/??/2021', desc2: 'Author: Buck' },
        '433': { title: "It's among us", desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '434': { title: 'Requiem Aeternam', desc1: 'Date: ??/??/2021', desc2: 'Author: Hiruma' },
        '435': { title: 'Clock Blocked', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '436': { title: 'Next Level', desc1: 'Date: ??/??/2021', desc2: 'Author: Hiruma' },
        '437': { title: 'Vendetta Fluid', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '438': { title: '1996-2020', desc1: 'Date: ??/??/2021', desc2: 'Author: Hiruma' },
        '439': { title: 'Home run', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '440': { title: 'Salty yet sweet', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '441': { title: 'ThirstRemover 3000', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '442': { title: 'Yes, we have it!', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '443': { title: 'Oreoreoreoreo', desc1: 'Date: ??/??/2021', desc2: 'Author: Buck' },
        '444': { title: 'Creation Engine', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '445': { title: 'We ordered more', desc1: 'Date: ??/??/2021', desc2: 'Author: Unknown' },
        '446': { title: 'Data is beautiful', desc1: 'Date: ??/??/2021', desc2: 'Author: Schrottii' },
        '447': { title: 'Party Rockers', desc1: 'Date: ??/??/2021', desc2: 'Author: Aloee (remade by TheKingofTrash)' },
        '448': { title: 'Quoit-unquoit', desc1: 'Date: ??/??/2021', desc2: 'Author: Hiruma' },
        '449': { title: 'Who ate it?', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '450': { title: 'Not for swimming', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '451': { title: 'Just Leaf it', desc1: 'Date: ??/??/2021', desc2: 'Author: Schrottii' },
        '452': { title: 'Resonance', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '453': { title: 'Give me food!', desc1: 'Date: ??/??/2021', desc2: 'Author: Den' },
        '454': { title: 'Flowey', desc1: 'Date: ??/??/2021', desc2: 'Author: Unknown' },
        '455': { title: '5 what?', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '456': { title: 'Blast from the Past', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '457': { title: "Where's the cheese?", desc1: 'Date: ??/??/2021', desc2: 'Author: Bird (edited by TheKingofTrash)' },
        '458': { title: 'Rotten!', desc1: 'Date: ??/??/2021', desc2: 'Author: Decastar2819' },
        '459': { title: 'Shipment Underway', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '460': { title: 'Any Colour You Like', desc1: 'Date: ??/??/2021', desc2: 'Author: Bird' },
        '461': { title: 'Stop right there!', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '462': { title: "Vito's Pizza", desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '463': { title: 'Home Remedy', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '464': { title: 'A cuboid for ants?', desc1: 'Date: ??/??/2021', desc2: 'Author: Hiruma' },
        '465': { title: 'Miraculous Matter', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '466': { title: 'Quack v4.0', desc1: 'Date: ??/??/2021', desc2: 'Author: Schrottii' },
        '467': { title: 'For the Literature Club', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '468': { title: 'Little Book of Horrors', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '469': { title: "I'm a happy camper!", desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '470': { title: 'The Earth As We Know It', desc1: 'Date: ??/??/2021', desc2: 'Author: Den' },
        '471': { title: 'Lamp From Above', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '472': { title: 'The Great Greed', desc1: 'Date: ??/??/2021', desc2: 'Author: Decastar2819 (edited by TheKingofTrash)' },
        '473': { title: "Who's to Blame?", desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '474': { title: 'Caprese Tower', desc1: 'Date: ??/??/2021', desc2: 'Author: Bird' },
        '475': { title: 'Aestheticsm', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '476': { title: 'Potassium Slices', desc1: 'Date: ??/??/2021', desc2: 'Author: Den' },
        '477': { title: 'Warp of Ruination', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '478': { title: 'Rubus', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '479': { title: 'Snow Leopard', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '480': { title: 'Peanut Butter Jelly Time', desc1: 'Date: ??/??/2021', desc2: 'Author: Decastar2819 (remade by TheKingofTrash)' },
        '481': { title: '29 too late', desc1: 'Date: ??/??/2021', desc2: 'Author: Hiruma (edited by TheKingofTrash)' },
        '482': { title: "Welders' Job", desc1: 'Date: ??/??/2021', desc2: 'Author: avexohsf' },
        '483': { title: 'Tome of Smartness', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '484': { title: 'Boss of all lockers', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '485': { title: 'Fashion Statement', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '486': { title: 'Arcanic Elevator', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '487': { title: 'Smell ya later!', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '488': { title: 'The Dust', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '489': { title: '8 to 16-Bit', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '490': { title: 'Crème de fraises', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '491': { title: 'Sparkly Taste', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '492': { title: 'This might sting...', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '493': { title: 'Roguelike', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '494': { title: 'The Strange World', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '495': { title: 'Dramatic Waxing', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '496': { title: 'New Generation', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '497': { title: 'Fruity!', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '498': { title: 'Bluish Gelatin', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '499': { title: 'Where are the monkeys?', desc1: 'Date: ??/??/2021', desc2: 'Author: Hiruma' },
        '500': { title: 'Job done!', desc1: 'Date: ??/??/2021', desc2: 'Author: klockowaty' },
        '501': { title: 'Road to yeet', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '502': { title: 'Janitor, Press Start!', desc1: 'Date: ??/??/2021', desc2: 'Author: Decastar2819' },
        '503': { title: 'aMAZEing', desc1: 'Date: ??/??/2021', desc2: 'Author: Buck' },
        '504': { title: "Let's Zill!", desc1: 'Date: ??/??/2021', desc2: 'Author: Bird' },
        '505': { title: 'Merging routine, set!', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '506': { title: 'Fire3', desc1: 'Date: ??/??/2021', desc2: 'Author: Decastar2819' },
        '507': { title: "Devil's Fury", desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '508': { title: 'Trippy Architecture', desc1: 'Date: ??/??/2021', desc2: 'Author: klockowaty' },
        '509': { title: 'Abandoned Garden', desc1: 'Date: ??/??/2021', desc2: 'Author: Decastar2819' },
        '510': { title: 'Citric Acid', desc1: 'Date: ??/??/2021', desc2: 'Author: Decastar2819' },
        '511': { title: "Gambling but it's Christmas", desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '512': { title: '12.65 V', desc1: 'Date: ??/??/2021', desc2: 'Author: klockowaty' },
        '513': { title: 'Portable Winter', desc1: 'Date: ??/??/2021', desc2: 'Author: Buck' },
        '514': { title: 'The Prototype', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '515': { title: 'Peppy Tincture', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '516': { title: 'Maize Candy', desc1: 'Date: ??/??/2021', desc2: 'Author: Decastar2819' },
        '517': { title: 'Pentagon of Devastation', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '518': { title: 'From the Garage', desc1: 'Date: ??/??/2021', desc2: 'Author: Decastar2819' },
        '519': { title: 'Triumvirate of Power', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '520': { title: 'Maple and Syrup', desc1: 'Date: ??/??/2021', desc2: 'Author: Decastar2819' },
        '521': { title: 'Bricks of Chocolate', desc1: 'Date: ??/??/2021', desc2: 'Author: TheKingofTrash' },
        '522': { title: 'You must construct...', desc1: 'Date: ??/??/2021', desc2: 'Author: Buck' },
        '523': { title: 'A Dose of Die', desc1: 'Date: ??/??/2022', desc2: 'Author: TheKingofTrash' },
        '524': { title: 'Point it here!', desc1: 'Date: ??/??/2022', desc2: 'Author: TheKingofTrash' },
        '525': { title: 'Lunch Box of the East', desc1: 'Date: ??/??/2022', desc2: 'Author: Rainbowflame' },
        '526': { title: 'Colorful energy', desc1: 'Date: ??/??/2022', desc2: 'Author: TheKingofTrash' },
        '527': { title: 'Press, Hold, Merge!', desc1: 'Date: ??/??/2022', desc2: 'Author: TheKingofTrash' },
        '528': { title: 'Grand master', desc1: 'Date: ??/??/2022', desc2: 'Author: klockowaty' },
        '529': { title: 'Memories', desc1: 'Date: ??/??/2022', desc2: 'Author: TheKingofTrash' },
        '530': { title: "Who's John?", desc1: 'Date: ??/??/2022', desc2: 'Author: TheKingofTrash' },
        '531': { title: 'Schrott says', desc1: 'Date: ??/??/2022', desc2: 'Author: TheKingofTrash' },
        '532': { title: 'Return of the Living Barrel', desc1: 'Date: ??/??/2022', desc2: 'Author: Decastar2819' },
        '533': { title: 'Did you try changing it?', desc1: 'Date: ??/??/2022', desc2: 'Author: TheKingofTrash' },
        '534': { title: 'Hexagonest Hexagon', desc1: 'Date: ??/??/2022', desc2: 'Author: TheKingofTrash' },
        '535': { title: "Gold N' Glory / Amazing Treasure!", desc1: 'Date: ??/??/2022', desc2: 'Author: Decastar2819' },
        '536': { title: 'Find the fragments', desc1: 'Date: ??/??/2022', desc2: 'Author: dwyer' },
        '537': { title: 'Limited Time Only', desc1: 'Date: ??/??/2022', desc2: 'Author: Decastar2819' },
        '538': { title: 'Longbow Acid / Nade out!', desc1: 'Date: ??/??/2022', desc2: 'Author: TheKingofTrash' },
        '539': { title: 'How much time left? / How much time to end?', desc1: 'Date: ??/??/2022', desc2: 'Author: klockowaty' },
        '540': { title: '*click* BOOM! / Watch yer step!', desc1: 'Date: ??/??/2022', desc2: 'Author: TheKingofTrash' },
        '541': { title: 'Inheritance', desc1: 'Date: ??/??/2022', desc2: 'Author: Hiruma' },
        '542': { title: '100% Cold Fusion / Upgrade complete!', desc1: 'Date: ??/??/2022', desc2: 'Author: TheKingofTrash' },
        '543': { title: 'The Conductor', desc1: 'Date: ??/??/2022', desc2: 'Author: TheKingofTrash' },
        '544': { title: 'Spooky & Scary Barrel', desc1: 'Date: ??/??/2022', desc2: 'Author: Decastar2819' },
        '545': { title: 'Planet 9', desc1: 'Date: ??/??/2022', desc2: 'Author: Den' },
        '546': { title: 'Defragmentation!', desc1: 'Date: ??/??/2022', desc2: 'Author: dwyer' },
        '547': { title: 'Go to the City', desc1: 'Date: ??/??/2022', desc2: 'Author: Aquarius (remade by Doshi)' },
        '548': { title: 'Special Space Mission', desc1: 'Date: ??/??/2022', desc2: 'Author: Doshi' },
        '549': { title: 'The Event', desc1: 'Date: ??/??/2022', desc2: 'Author: Decastar2819' },
        '550': { title: 'EF5', desc1: 'Date: ??/??/2022', desc2: 'Author: Doshi' },
        '551': { title: 'Alien Lexicon', desc1: 'Date: ??/??/2022', desc2: 'Author: Roziru' },
        '552': { title: '4k RPM', desc1: 'Date: ??/??/2022', desc2: 'Author: Roziru' },
        '553': { title: 'Maple is too popular', desc1: 'Date: ??/??/2022', desc2: 'Author: Schrottii' },
        '554': { title: 'Parallel Hollywood', desc1: 'Date: ??/??/2022', desc2: 'Author: klockowaty' },
        '555': { title: 'Oddeven', desc1: 'Date: ??/??/2022', desc2: 'Author: avexohsf' },
        '556': { title: "Decrypter's Toy", desc1: 'Date: ??/??/2022', desc2: 'Author: Gegiojon' },
        '557': { title: 'Dank and Damp Wiring', desc1: 'Date: ??/??/2022', desc2: 'Author: TheKingofTrash' },
        '558': { title: 'Can Cake Can You?', desc1: 'Date: ??/??/2022', desc2: 'Author: Rainbowflame' },
        '559': { title: 'Atom Chronicles', desc1: 'Date: ??/??/2022', desc2: 'Author: avexohsf' },
        '560': { title: 'A Home for Hammy', desc1: 'Date: ??/??/2022', desc2: 'Author: Roziru' },
        '561': { title: "Dungeon Crawlin'", desc1: 'Date: ??/??/2022', desc2: 'Author: TheKingofTrash' },
        '562': { title: 'Here in My Garage', desc1: 'Date: ??/??/2022', desc2: 'Author: TheKingofTrash' },
        '563': { title: 'With Comfort', desc1: 'Date: ??/??/2022', desc2: 'Author: klockowaty' },
        '564': { title: 'The Origins', desc1: 'Date: ??/??/2022', desc2: 'Author: TheKingofTrash' },
        '565': { title: 'The Ultimate Run', desc1: 'Date: ??/??/2022', desc2: 'Author: brorlol' },
        '566': { title: 'King of Barrels, Alfred', desc1: 'Date: ??/??/2022', desc2: 'Author: TheKingofTrash' },
        '567': { title: 'Edible?', desc1: 'Date: ??/??/2022', desc2: 'Author: avexohsf' },
        '568': { title: 'PC Ancestry', desc1: 'Date: ??/??/2022', desc2: 'Author: klockowaty' },
        '569': { title: 'Fast & Sharp!', desc1: 'Date: ??/??/2022', desc2: 'Author: TheKingofTrash' },
        '570': { title: 'Surprise attack!', desc1: 'Date: ??/??/2022', desc2: 'Author: TheKingofTrash' },
        '571': { title: 'Vampire Slaying Powder', desc1: 'Date: ??/??/2022', desc2: 'Author: TheKingofTrash' },
        '572': { title: 'Far Away...', desc1: 'Date: ??/??/2022', desc2: 'Author: Decastar2819' },
        '573': { title: 'Please, beehive!', desc1: 'Date: ??/??/2022', desc2: 'Author: TheKingofTrash' },
        '574': { title: '1 Million Scoville', desc1: 'Date: ??/??/2022', desc2: 'Author: Roziru' },
        '575': { title: 'Thai Lemon', desc1: 'Date: ??/??/2022', desc2: 'Author: Roziru' },
        '576': { title: "Stoker's Hearth", desc1: 'Date: ??/??/2022', desc2: 'Author: Decastar2819' },
        '577': { title: 'Original Recipe', desc1: 'Date: ??/??/2022', desc2: 'Author: Decastar2819' },
        '578': { title: 'Cooper, do you copy?', desc1: 'Date: ??/??/2022', desc2: 'Author: TheKingofTrash' },
        '579': { title: 'Annoying Aviator', desc1: 'Date: ??/??/2022', desc2: 'Author: TheKingofTrash' },
        '580': { title: 'Scrapeo and Juliet', desc1: 'Date: ??/??/2022', desc2: 'Author: Bird' },
        '581': { title: 'The Bouncer', desc1: 'Date: ??/??/2022', desc2: 'Author: TheKingofTrash' },
        '582': { title: 'Error 503', desc1: 'Date: ??/??/2022', desc2: 'Author: klockowaty' },
        '583': { title: 'Fairy Dust', desc1: 'Date: ??/??/2022', desc2: 'Author: Roziru' },
        '584': { title: '6 feet deep', desc1: 'Date: ??/??/2022', desc2: 'Author: Schrottii' },
        '585': { title: 'Anti-Fire 5', desc1: 'Date: ??/??/2022', desc2: 'Author: TheKingofTrash' },
        '586': { title: 'In 50 years...', desc1: 'Date: ??/??/2022', desc2: 'Author: Roziru' },
        '587': { title: "Artist's Arsenal", desc1: 'Date: ??/??/2022', desc2: 'Author: Roziru' },
        '588': { title: 'Sundown', desc1: 'Date: ??/??/2022', desc2: 'Author: Roziru' },
        '589': { title: 'Smooth, cool, nutritious', desc1: 'Date: ??/??/2022', desc2: 'Author: Roziru' },
        '590': { title: 'Merge or Click?', desc1: 'Date: ??/??/2022', desc2: 'Author: Roziru' },
        '591': { title: 'From the Shadows', desc1: 'Date: ??/??/2022', desc2: 'Author: TheKingofTrash' },
        '592': { title: 'The Cave of the Barrels', desc1: 'Date: ??/??/2022', desc2: 'Author: TheKingofTrash' },
        '593': { title: 'Power Your Scrap', desc1: 'Date: ??/??/2022', desc2: 'Author: Roziru' },
        '594': { title: "You just got Macaroon'd!", desc1: 'Date: ??/??/2022', desc2: 'Author: Roziru' },
        '595': { title: 'Robotic Choco', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash' },
        '596': { title: 'Simplified Gasket', desc1: 'Date: ??/??/2023', desc2: 'Author: Roziru' },
        '597': { title: 'I R Incremental', desc1: 'Date: ??/??/2023', desc2: 'Author: Roziru' },
        '598': { title: 'Taste the Vapor', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash' },
        '599': { title: 'Book of Doom', desc1: 'Date: ??/??/2023', desc2: 'Author: avexohsf' },
        '600': { title: 'Another Milestone', desc1: 'Date: ??/??/2023', desc2: 'Author: Decastar2819' },
        '601': { title: 'Scrapels 2 - The Souring', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash' },
        '602': { title: 'ModPocket Visualizer Deluxe', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash' },
        '603': { title: 'Electric Flame', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash' },
        '604': { title: 'Nix Civilizations', desc1: 'Date: ??/??/2023', desc2: 'Author: Decastar2819' },
        '605': { title: 'Scraburger', desc1: 'Date: ??/??/2023', desc2: 'Author: Decastar2819' },
        '606': { title: 'To the bottom of the sea!', desc1: 'Date: ??/??/2023', desc2: 'Author: Roziru' },
        '607': { title: 'Which way do we go?', desc1: 'Date: ??/??/2023', desc2: 'Author: Roziru' },
        '608': { title: 'Queso De Bola / Scrapple', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash' },
        '609': { title: 'Baby slice it right!', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash' },
        '610': { title: 'Dangerous Blob of Goo', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash' },
        '611': { title: 'Feng Shui', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash' },
        '612': { title: 'Scrapuzzle', desc1: 'Date: ??/??/2023', desc2: 'Author: Roziru' },
        '613': { title: 'No diving allowed', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash' },
        '614': { title: 'Campfire Munchies', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash' },
        '615': { title: 'A Crown for a King', desc1: 'Date: ??/??/2023', desc2: 'Author: Roziru' },
        '616': { title: 'Kabosu', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash' },
        '617': { title: 'Malevolent Proliferation', desc1: 'Date: ??/??/2023', desc2: 'Author: Decastar2819' },
        '618': { title: 'Hung out to Dry', desc1: 'Date: ??/??/2023', desc2: 'Author: Roziru' },
        '619': { title: 'Always watching', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash' },
        '620': { title: 'The Hero Called H', desc1: 'Date: ??/??/2023', desc2: 'Author: Aloee' },
        '621': { title: 'Cornbread', desc1: 'Date: ??/??/2023', desc2: 'Author: Roziru' },
        '622': { title: 'Ascorbic Beam', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash' },
        '623': { title: 'S-800', desc1: 'Date: ??/??/2023', desc2: 'Author: Roziru' },
        '624': { title: 'Shimmering Aether', desc1: 'Date: ??/??/2023', desc2: 'Author: Decastar2819' },
        '625': { title: 'Magnet Attractor Mk.IV', desc1: 'Date: ??/??/2023', desc2: 'Author: Roziru' },
        '626': { title: 'Fur of the Tiger', desc1: 'Date: ??/??/2023', desc2: 'Author: Roziru' },
        '627': { title: 'Kittyball!', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash' },
        '628': { title: 'Another Dollar Wasted', desc1: 'Date: ??/??/2023', desc2: 'Author: Decastar2819' },
        '629': { title: 'Free hook-ups!', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash' },
        '630': { title: 'Chess... flavored?', desc1: 'Date: ??/??/2023', desc2: 'Author: Schrottii' },
        '631': { title: 'Lunar Potion', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash' },
        '632': { title: 'Old Science', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash' },
        '633': { title: 'Beta Pictoris', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash' },
        '634': { title: 'Pip-Duck 4000', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash' },
        '635': { title: 'Shiny Barrel', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash' },
        '636': { title: 'Going nuclear', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash' },
        '637': { title: 'Copper Tower', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash' },
        '638': { title: 'Ultimate gamer move!', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash' },
        '639': { title: 'Eldritch hatching grounds', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash' },
        '640': { title: 'Electric Eye', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash' },
        '641': { title: 'TechCube 3000', desc1: 'Date: ??/??/2023', desc2: 'Author: Roziru' },
        '642': { title: 'Finger Drug', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash' },
        '643': { title: 'Artistic Revolution', desc1: 'Date: ??/??/2023', desc2: 'Author: Roziru' },
        '644': { title: 'Scrapdines', desc1: 'Date: ??/??/2023', desc2: 'Author: Decastar2819' },
        '645': { title: 'Pink Simulation', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash' },
        '646': { title: 'RETURN THE SLAAAB', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash' },
        '647': { title: 'Poison Pool', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash' },
        '648': { title: 'ScrapTOS', desc1: 'Date: ??/??/2023', desc2: 'Author: Roziru' },
        '649': { title: 'Stone & Dirt', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash' },
        '650': { title: 'Jugs and Slopers', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash (Original by Roziru)' },
        '651': { title: "Please Don't Die", desc1: 'Date: ??/??/2023', desc2: 'Author: Decastar2819' },
        '652': { title: 'Scraptory', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash' },
        '653': { title: 'Cleats', desc1: 'Date: ??/??/2023', desc2: 'Author: hiruma (remade by TheKingofTrash)' },
        '654': { title: 'Sweet Memories', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash' },
        '655': { title: 'Please wait 60 seconds!', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash' },
        '656': { title: 'Stop... you failed!', desc1: 'Date: ??/??/2023', desc2: 'Author: Roziru' },
        '657': { title: 'NOSE', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash' },
        '658': { title: 'Grass Puppy / Her favorite drink (Before 11.5)', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash' },
        '659': { title: 'Fairy Acid', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash' },
        '660': { title: "Don't put...", desc1: 'Date: ??/??/2023', desc2: 'Author: Barbaris (reworked by Roziru)' },
        '661': { title: 'Peter', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash' },
        '662': { title: 'The 1,000,000th Star', desc1: 'Date: ??/??/2023', desc2: 'Author: Schrottii (reworked by Roziru)' },
        '663': { title: 'Shapeshift', desc1: 'Date: ??/??/2023', desc2: 'Author: Roziru' },
        '664': { title: 'Acceleration Road', desc1: 'Date: ??/??/2023', desc2: 'Author: Roziru' },
        '665': { title: 'Can I Sell This?', desc1: 'Date: ??/??/2023', desc2: 'Author: TheKingofTrash' },
        '666': { title: 'Barrel to Hell', desc1: 'Date: ??/??/2023', desc2: 'Author: Original by NXISE and TheKingofTrash, reworked by Endte and Schrottii' },
        '667': { title: 'This milk is nuts!', desc1: 'Date: ??/??/2024', desc2: 'Author: TheKingofTrash' },
        '668': { title: 'Stop Meat Consumption!', desc1: 'Date: ??/??/2024', desc2: 'Author: TheKingofTrash' },
        '669': { title: "Where's the Corn?", desc1: 'Date: ??/??/2024', desc2: 'Author: TheKingofTrash' },
        '670': { title: 'No Electricity Bills', desc1: 'Date: ??/??/2024', desc2: 'Author: Roziru' },
        '671': { title: "Where's the Base?", desc1: 'Date: ??/??/2024', desc2: 'Author: Dabby' },
        '672': { title: 'A Coat of Nero', desc1: 'Date: ??/??/2024', desc2: 'Author: Bird' },
        '673': { title: 'Nine Inch Barrels', desc1: 'Date: ??/??/2024', desc2: 'Author: TheKingofTrash' },
        '674': { title: 'Spice up your life!', desc1: 'Date: ??/??/2024', desc2: 'Author: TheKingofTrash' },
        '675': { title: 'Not a Bowl!', desc1: 'Date: ??/??/2024', desc2: 'Author: Dabby' },
        '676': { title: 'How to watch this?', desc1: 'Date: ??/??/2024', desc2: 'Author: Roziru' },
        '677': { title: 'Better than Wood!', desc1: 'Date: ??/??/2024', desc2: 'Author: Roziru' },
        '678': { title: 'Ice-B', desc1: 'Date: ??/??/2024', desc2: 'Author: Decastar2819' },
        '679': { title: 'Frosty v. Yule', desc1: 'Date: ??/??/2024', desc2: 'Author: Roziru' },
        '680': { title: 'Recycle Hole', desc1: 'Date: ??/??/2024', desc2: 'Author: Roziru' },
        '681': { title: 'Festive Housing', desc1: 'Date: ??/??/2024', desc2: 'Author: klockowaty' },
        '682': { title: 'Potion to Self-Ignite', desc1: 'Date: ??/??/2024', desc2: 'Author: TheKingofTrash' },
        '683': { title: 'Compact Glow', desc1: 'Date: ??/??/2024', desc2: 'Author: Roziru' },
        '684': { title: 'Keep Your Neck Warm!', desc1: 'Date: ??/??/2024', desc2: 'Author: Roziru' },
        '685': { title: 'Verdure', desc1: 'Date: ??/??/2024', desc2: 'Author: Roziru' },
        '686': { title: 'The Power of your Soul', desc1: 'Date: ??/??/2024', desc2: 'Author: Roziru' },
        '687': { title: "I'm lost! help", desc1: 'Date: ??/??/2024', desc2: 'Author: Roziru' },
        '688': { title: "I'm colorblind! help", desc1: 'Date: ??/??/2024', desc2: 'Author: Roziru' },
        '689': { title: 'Scrapyard Jazz', desc1: 'Date: ??/??/2024', desc2: 'Author: TheKingofTrash' },
        '690': { title: 'XOXO', desc1: 'Date: ??/??/2024', desc2: 'Author: Roziru' },
        '691': { title: 'Cherry On Top', desc1: 'Date: ??/??/2024', desc2: 'Author: Roziru' },
        '692': { title: 'Heavy Construction', desc1: 'Date: ??/??/2024', desc2: 'Author: Roziru' },
        '693': { title: 'Pink Layers', desc1: 'Date: ??/??/2024', desc2: 'Author: TheKingofTrash' },
        '694': { title: 'Knife Hit', desc1: 'Date: ??/??/2024', desc2: 'Author: Den' },
        '695': { title: 'Final Castle', desc1: 'Date: ??/??/2024', desc2: 'Author: Roziru (Original by Hiruma)' },
        '696': { title: 'Life finds a Way', desc1: 'Date: ??/??/2024', desc2: 'Author: Cyber' },
        '697': { title: 'Ultimate Heat Heater', desc1: 'Date: ??/??/2024', desc2: 'Author: TheKingofTrash' },
        '698': { title: "Where's Happy Juice?", desc1: 'Date: ??/??/2024', desc2: 'Author: Roziru' },
        '699': { title: 'Floats in a Tub!', desc1: 'Date: ??/??/2024', desc2: 'Author: TheKingofTrash' },
        '700': { title: 'Heart of the Sea', desc1: 'Date: ??/??/2024', desc2: 'Author: Roziru' },
        '701': { title: "Where's the Beach?", desc1: 'Date: ??/??/2024', desc2: 'Author: Dabby' },
        '702': { title: 'Next Level Gaming', desc1: 'Date: ??/??/2024', desc2: 'Author: Roziru' },
        '703': { title: 'Magma Cone', desc1: 'Date: ??/??/2024', desc2: 'Author: Den' },
        '704': { title: 'Hill of the Orient', desc1: 'Date: ??/??/2024', desc2: 'Author: Decastar2819' },
        '705': { title: 'Shocker!', desc1: 'Date: ??/??/2024', desc2: 'Author: TheKingofTrash' },
        '706': { title: 'Yerba Mate', desc1: 'Date: ??/??/2024', desc2: 'Author: TheKingofTrash' },
        '707': { title: "Nature's Pitchers", desc1: 'Date: ??/??/2024', desc2: 'Author: Roziru' },
        '708': { title: 'Crack Me', desc1: 'Date: ??/??/2024', desc2: 'Author: TheKingofTrash' },
        '709': { title: 'A+', desc1: 'Date: ??/??/2024', desc2: 'Author: avexohsf' },
        '710': { title: 'Mystery Pods', desc1: 'Date: ??/??/2024', desc2: 'Author: Buck' },
        '711': { title: 'Deadly Laser 250', desc1: 'Date: ??/??/2024', desc2: 'Author: TheKingofTrash' },
        '712': { title: "That didn't age well", desc1: 'Date: ??/??/2024', desc2: 'Author: Schrottii' },
        '713': { title: 'CYMK', desc1: 'Date: ??/??/2024', desc2: 'Author: Buck' },
        '714': { title: 'Triple-Double', desc1: 'Date: ??/??/2024', desc2: 'Author: Dabby' },
        '715': { title: 'Daydreaming', desc1: 'Date: ??/??/2024', desc2: 'Author: avexohsf' },
        '716': { title: 'Warhol', desc1: 'Date: ??/??/2024', desc2: 'Author: Gegiojon (Remade by TheKingofTrash)' },
        '717': { title: 'Futhark', desc1: 'Date: ??/??/2024', desc2: 'Author: Schrottii' },
        '718': { title: 'Lost Parcel', desc1: 'Date: ??/??/2024', desc2: 'Author: TheKingofTrash' },
        '719': { title: 'Baby pink!', desc1: 'Date: ??/??/2024', desc2: 'Author: TheKingofTrash' },
        '720': { title: 'Beer Food', desc1: 'Date: ??/??/2024', desc2: 'Author: Schrottii' },
        '721': { title: 'Human Resources', desc1: 'Date: ??/??/2024', desc2: 'Author: klockowaty' },
        '722': { title: 'Kingdom Defender', desc1: 'Date: ??/??/2024', desc2: 'Author: Cyber' },
        '723': { title: 'Bocchi', desc1: 'Date: ??/??/2024', desc2: 'Author: Buck' },
        '725': { title: 'Green Bunny', desc1: 'Date: ??/??/2024', desc2: 'Author: Schrottii' },
        '726': { title: 'The Mirror to Nowhere', desc1: 'Date: ??/??/2024', desc2: 'Author: Unknown' },
        '727': { title: 'More sides - more fun', desc1: 'Date: ??/??/2024', desc2: 'Author: Dabby' },
        '728': { title: 'Inky Writing', desc1: 'Date: ??/??/2024', desc2: 'Author: Bird' },
        '729': { title: 'Rome & Venice', desc1: 'Date: ??/??/2024', desc2: 'Author: Cyber' },
        '730': { title: 'Celebrate Death', desc1: 'Date: ??/??/2024', desc2: 'Author: Dabby' },
        '731': { title: 'Sigh... unzips pants', desc1: 'Date: ??/??/2024', desc2: 'Author: Roziru' },
        '732': { title: 'EXP: 11/28/2004', desc1: 'Date: ??/??/2024', desc2: 'Author: TheKingofTrash' },
        '733': { title: 'Mad Hat Solution', desc1: 'Date: ??/??/2024', desc2: 'Author: TheKingofTrash' },
        '734': { title: 'ScrapRPG', desc1: 'Date: ??/??/2024', desc2: 'Author: Den' },
        '735': { title: 'Purple, and forgotten', desc1: 'Date: ??/??/2024', desc2: 'Author: TheKingofTrash' },
        '736': { title: 'The Perfect Tower', desc1: 'Date: ??/??/2024', desc2: 'Author: Decastar2819' },
        '737': { title: 'The Desert Rose', desc1: 'Date: ??/??/2024', desc2: 'Author: TheKingofTrash' },
        '738': { title: 'SSD GigaEnergy', desc1: 'Date: ??/??/2024', desc2: 'Author: TheKingofTrash' },
        '739': { title: 'Press "E" to Disarm', desc1: 'Date: ??/??/2024', desc2: 'Author: TheKingofTrash' },
        '740': { title: 'The numbers, Mason!', desc1: 'Date: ??/??/2024', desc2: 'Author: Roziru' },
        '741': { title: 'Bald Bird', desc1: 'Date: ??/??/2024', desc2: 'Author: Cyber' },
        '742': { title: 'Gems of Power', desc1: 'Date: ??/??/2024', desc2: 'Author: TheKingofTrash' },
        '743': { title: '"Frightening"', desc1: 'Date: ??/??/2024', desc2: 'Author: Roziru' },
        '744': { title: 'Return to monke!', desc1: 'Date: ??/??/2024', desc2: 'Author: TheKingofTrash' },
        '745': { title: 'Officer Duck', desc1: 'Date: ??/??/2024', desc2: 'Author: Dabby' },
        '746': { title: '50% more quiet!', desc1: 'Date: ??/??/2024', desc2: 'Author: TheKingofTrash' },
        '748': { title: 'Do not throw', desc1: 'Date: ??/??/2024', desc2: 'Author: Roziru' },
        '749': { title: 'Getting Funky With Gravity', desc1: 'Date: ??/??/2024', desc2: 'Author: TheKingofTrash' },
        '750': { title: 'Good, Bad, and Quacky', desc1: 'Date: ??/??/2024', desc2: 'Author: Cyber (A remake of a barrel by TinyZ.)' },
        '751': { title: 'A Starry Sea', desc1: 'Date: ??/??/2024', desc2: 'Author: Den' },
        '752': { title: 'Plants as White as Snow', desc1: 'Date: ??/??/2024', desc2: 'Author: Decastar2819 (A reference to the Greenhouse area in Undertale Yellow, an Undertale fan game.)' },
        '753': { title: 'Cretaceous', desc1: 'Date: ??/??/2024', desc2: 'Author: Cyber (A remake of a barrel by Claudio Vestita.)' },
        '755': { title: 'Good Morning', desc1: 'Date: ??/??/2024', desc2: 'Author: Schrottii' },
        '756': { title: "Don't get frostbite!", desc1: 'Date: ??/??/2024', desc2: 'Author: TheKingofTrash' },
        '757': { title: 'Determined to Burn', desc1: 'Date: ??/??/2024', desc2: 'Author: TheKingofTrash' },
        '758': { title: 'Taking shape', desc1: 'Date: ??/??/2024', desc2: 'Author: TheKingofTrash' },
        '759': { title: 'Overgrowth', desc1: 'Date: ??/??/2024', desc2: 'Author: TheKingofTrash' },
        '760': { title: 'Shines Eternal', desc1: 'Date: ??/??/2024', desc2: 'Author: TheKingofTrash' },
        '761': { title: 'Erosion', desc1: 'Date: ??/??/2024', desc2: 'Author: TheKingofTrash' },
        '762': { title: 'Updraft', desc1: 'Date: ??/??/2024', desc2: 'Author: TheKingofTrash' },
        '763': { title: "Nature's Coat", desc1: 'Date: ??/??/2025', desc2: 'Author: Dabby' },
        '764': { title: 'Revved & Ready', desc1: 'Date: ??/??/2025', desc2: 'Author: TheKingofTrash' },
        '765': { title: 'The Sandman', desc1: 'Date: ??/??/2025', desc2: 'Author: Cyber' },
        '766': { title: 'Double Playfield', desc1: 'Date: ??/??/2025', desc2: 'Author: Dabby (A Remake of a barrel by Champion.)' },
        '767': { title: 'Not Again!', desc1: 'Date: ??/??/2025', desc2: 'Author: Cyber (A Remake of a barrel by unknown artist.)' },
        '768': { title: 'Creme Brulee', desc1: 'Date: ??/??/2025', desc2: 'Author: Dabby' },
        '769': { title: 'Psycho Beach Ball', desc1: 'Date: ??/??/2025', desc2: 'Author: Dabby' },
        '770': { title: 'Carry on!', desc1: 'Date: ??/??/2025', desc2: 'Author: TheKingofTrash' },
        '771': { title: 'Back to school!', desc1: 'Date: ??/??/2025', desc2: 'Author: Cyber' },
        '772': { title: 'Precious Cinnamon Rolls', desc1: 'Date: ??/??/2025', desc2: 'Author: TheKingofTrash' },
        '773': { title: 'Fun Fare', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '774': { title: 'Absolute Difference', desc1: 'Date: ??/??/2025', desc2: 'Author: Cyber (A Remake of a barrel by unknown artist.)' },
        '775': { title: "Rich Man's Shroom", desc1: 'Date: ??/??/2025', desc2: 'Author: TheKingofTrash' },
        '776': { title: "The Sea's Blessing", desc1: 'Date: ??/??/2025', desc2: 'Author: TheKingofTrash' },
        '777': { title: 'Molten Cubestruction', desc1: 'Date: ??/??/2025', desc2: 'Author: TheKingofTrash' },
        '778': { title: 'The End.', desc1: 'Date: ??/??/2025', desc2: 'Author: Cyber (A Remake of a barrel by unknown artist.)' },
        '779': { title: 'Embraced Energy Extreme', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '780': { title: '250 Carat Lemon', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '781': { title: 'Bake for 10-12 Minutes', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '782': { title: 'Any In Small', desc1: 'Date: ??/??/2025', desc2: 'Author: Cyber' },
        '783': { title: 'Three- course juice!', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '784': { title: 'The Great Scrap Drama', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '785': { title: 'Pumpkin Monster II', desc1: 'Date: ??/??/2025', desc2: 'Author: Cyber' },
        '786': { title: "Sailor's best friend", desc1: 'Date: ??/??/2025', desc2: 'Author: Cyber' },
        '787': { title: 'Lethal Lava Cake', desc1: 'Date: ??/??/2025', desc2: 'Author: Cyber (Cyber made this cake barrel for his birthday :D.)' },
        '788': { title: 'Time to Get Out!!!', desc1: 'Date: ??/??/2025', desc2: 'Author: Cyber' },
        '789': { title: 'More than Coffee', desc1: 'Date: ??/??/2025', desc2: 'Author: Cyber' },
        '790': { title: 'All You Can Merge', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '791': { title: 'Million Merge Club', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '792': { title: 'Drink to be spooked', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '794': { title: 'Layers of Water', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '795': { title: 'Valentine Concoction', desc1: 'Date: ??/??/2025', desc2: 'Author: Decastar2819' },
        '796': { title: 'Countryside', desc1: 'Date: ??/??/2025', desc2: 'Author: Stanky Leg' },
        '797': { title: 'All the Curves', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '798': { title: 'Wrench Wries', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '799': { title: 'Caffeine Overload', desc1: 'Date: ??/??/2025', desc2: 'Author: Schrottii' },
        '800': { title: 'Octo-Milestone', desc1: 'Date: ??/??/2025', desc2: 'Author: Cyber' },
        '801': { title: 'Solve It or Eat It', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '802': { title: 'Call Me in Yen!', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '803': { title: 'Scales to Scale', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '804': { title: 'Wisdom Hourglass', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '805': { title: 'Modern Solutions', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '806': { title: 'The Ultimate Expression', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '807': { title: '99942', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '808': { title: 'Give me your Games!', desc1: 'Date: ??/??/2025', desc2: 'Author: Cyber' },
        '809': { title: 'Tower of the Evil Queen', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '810': { title: 'Milkshake', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '811': { title: 'Writing In Ruby', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '812': { title: 'Back on Track', desc1: 'Date: ??/??/2025', desc2: 'Author: Cyber' },
        '813': { title: 'Celestial Reflections', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '814': { title: 'Deuce!', desc1: 'Date: ??/??/2025', desc2: 'Author: Dabby' },
        '815': { title: 'My Own Prison', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '816': { title: 'Guardian of Fire', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '817': { title: 'The Majestic Waterfall', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '818': { title: 'Gifts for You!', desc1: 'Date: ??/??/2025', desc2: 'Author: Cyber' },
        '819': { title: 'It Might Seem Crazy', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '820': { title: 'Coal for You!', desc1: 'Date: ??/??/2025', desc2: 'Author: Cyber' },
        '821': { title: 'One Credit & One Track', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '822': { title: 'Forever Frozen', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '823': { title: 'Bought With Love', desc1: 'Date: ??/??/2025', desc2: 'Author: Schrottii' },
        '824': { title: 'Error: Tentacles', desc1: 'Date: ??/??/2025', desc2: 'Author: TheKingOfTrash' },
        '825': { title: 'Drill Barrel Drill', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '826': { title: '24K-arat', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '827': { title: 'Runic Ruby Energy', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '828': { title: 'Software Tower', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '829': { title: 'Royal X', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '830': { title: 'Copperpunk', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '831': { title: "Nymph's Dream", desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '832': { title: 'Noble Performance', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '833': { title: 'Crimson Witch', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '834': { title: 'Artifact to Impact', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '835': { title: 'We Want More of the Same', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '836': { title: 'Champion of the World', desc1: 'Date: ??/??/2025', desc2: 'Author: Dabby' },
        '837': { title: 'Fellow Pedestrians', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '838': { title: "I've Been to Japan", desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '839': { title: 'Blizzard Strayer', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '840': { title: 'Long Nature', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '841': { title: 'Quattro Patatine', desc1: 'Date: ??/??/2025', desc2: 'Author: TheKingOfTrash' },
        '842': { title: 'Soul Compassion', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '843': { title: "Please Don't Graffiti Me", desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '844': { title: 'Bigger Storage', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '845': { title: 'Her favorite drink', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '846': { title: 'FREEDOM!!!', desc1: 'Date: ??/??/2025', desc2: 'Author: Dabby' },
        '847': { title: 'Golden Valentine', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '848': { title: 'Desert of the Past', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '849': { title: 'Work-Life Balance', desc1: 'Date: ??/??/2025', desc2: 'Author: Cyber' },
        '850': { title: 'Temple of Claws', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '851': { title: 'Scrap Spray', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '852': { title: 'Factorial Pressure', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '853': { title: 'TRX', desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '854': { title: "The Earth's... Core?", desc1: 'Date: ??/??/2025', desc2: 'Author: TheKingOfTrash' },
        '855': { title: "How's the Weather?", desc1: 'Date: ??/??/2025', desc2: 'Author: Roziru' },
        '856': { title: 'Balanced Diet', desc1: 'Date: ??/??/2025', desc2: 'Author: Cyber' },
        '857': { title: "Where's the Doctor?", desc1: 'Date: ??/??/2025', desc2: 'Author: Cyber' },
        '858': { title: 'Ow, spikey', desc1: 'Date: ??/??/2025', desc2: 'Author: Cyber' },
        '859': { title: 'Minion Food', desc1: 'Date: ??/??/2025', desc2: 'Author: Cyber' },
        '860': { title: 'A vocal trend', desc1: 'Date: ??/??/2025', desc2: 'Author: Cyber' },
        '861': { title: "Sour'n Sweet", desc1: 'Date: ??/??/2025', desc2: 'Author: Cyber' },
        '862': { title: 'Not the bird!', desc1: 'Date: ??/??/2025', desc2: 'Author: Cyber' },
        '863': { title: "Where's the Dragon?", desc1: 'Date: ??/??/2025', desc2: 'Author: Cyber' },
        '864': { title: 'Clockwork', desc1: 'Date: ??/??/2025', desc2: 'Author: Cyber' },
        '865': { title: 'Coward!', desc1: 'Date: ??/??/2025', desc2: 'Author: Cyber' },
        '866': { title: 'Slice of Hapiness', desc1: 'Date: ??/??/2025', desc2: 'Author: Cyber' },
        '867': { title: 'Blue Teeth', desc1: 'Date: ??/??/2025', desc2: 'Author: Cyber' },
        '868': { title: 'I am passionate', desc1: 'Date: ??/??/2025', desc2: 'Author: Cyber' },
        '869': { title: 'Who lives in a...', desc1: 'Date: ??/??/2025', desc2: 'Author: Cyber' },
        '870': { title: 'Cocnutnut', desc1: 'Date: ??/??/2025', desc2: 'Author: Cyber' },

            //Not-In-Game Barrels
        
        '871': { title: 'Broken vase barrel', desc1: 'Date: ??/??/2025', desc2: 'Author: Bird' },
        '872': { title: 'Bubble barrel', desc1: 'Date: 21/07/2022', desc2: 'Author: Bird' },
        '873': { title: 'Caprese tower', desc1: 'Date: 21/07/2022', desc2: 'Author: Bird' },
        '874': { title: 'Point Of View', desc1: 'Date: 21/07/2022', desc2: 'Author: Bird' },
        '875': { title: 'Fake plastic tree', desc1: 'Date: 21/07/2022', desc2: 'Author: Bird' },
        '876': { title: 'Pasley gps barrel 2', desc1: 'Date: 21/07/2022', desc2: 'Author: Bird' },
        '877': { title: 'Rainbow heptagon', desc1: 'Date: 21/07/2022', desc2: 'Author: Bird' },
        '878': { title: 'Tambourine', desc1: 'Date: 21/07/2022', desc2: 'Author: Bird' },
        '879': { title: '???', desc1: 'Date: ??/??/????', desc2: 'Author: Buck' },
        '880': { title: 'fare box on buses in Japan', desc1: 'Date: 29/01/2025', desc2: 'Author: Buck' },
        '881': { title: 'Wrong lever', desc1: 'Date: 06/09/2021', desc2: 'Author: Buck' },
        '882': { title: 'Quill in ink cartridge', desc1: 'Date: 06/09/2021', desc2: 'Author: Buck' },
        '883': { title: '"Im Different"', desc1: 'Date: 06/09/2021', desc2: 'Author: Buck' },
        '884': { title: 'A magnet barrel!', desc1: 'Date: 06/09/2021', desc2: 'Author: Buck' },
        '885': { title: 'Portable Winter', desc1: 'Date: 06/09/2021', desc2: 'Author: Buck' },
        '886': { title: '???', desc1: 'Date: 06/09/2021', desc2: 'Author: Buck' },
        '887': { title: 'Rope', desc1: 'Date: 06/09/2021', desc2: 'Author: Buck' },
        '888': { title: 'Spring', desc1: 'Date: 06/09/2021', desc2: 'Author: Buck' },
        '889': { title: 'aMAZEing', desc1: 'Date: 06/09/2021', desc2: 'Author: Buck' },
        '890': { title: 'Bocchi', desc1: 'Date: 20/07/2023', desc2: 'Author: Buck' },
        '891': { title: 'A nod to The Witness', desc1: 'Date: 20/07/2023', desc2: 'Author: Buck' },
        '892': { title: 'Stata Center', desc1: 'Date: 20/07/2023', desc2: 'Author: Buck' },
        '893': { title: 'CYMK', desc1: 'Date: 11/01/2024', desc2: 'Author: Buck' },
        '894': { title: 'Mystery Pods', desc1: 'Date: 27/03/2024', desc2: 'Author: Buck' },
        '895': { title: 'Corn', desc1: 'Date: 06/12/2025', desc2: 'Author: Cyber' },
        '896': { title: 'Neon Open Sign', desc1: 'Date: 08/01/2026', desc2: 'Author: Cyber' },
        '897': { title: 'Blue Pink blob', desc1: 'Date: 11/01/2026', desc2: 'Author: Cyber' },
        '898': { title: 'Glowey Bottle', desc1: 'Date: 28/12/2025', desc2: 'Author: Cyber' },
        '899': { title: 'Lemon', desc1: 'Date: 28/12/2025', desc2: 'Author: Cyber' },
        '900': { title: 'Pomegranate', desc1: 'Date: 28/12/2025', desc2: 'Author: Cyber' },
        '901': { title: 'Pumpkin', desc1: 'Date: 06/12/2025', desc2: 'Author: Cyber' },
        '902': { title: 'Tomato', desc1: 'Date: 06/12/2025', desc2: 'Author: Cyber' },
        '903': { title: 'Barrel Design Creep', desc1: 'Date: 25/07/2025', desc2: 'Author: Schrottii' },
        '904': { title: 'Californisland', desc1: 'Date: 04/08/2025', desc2: 'Author: Schrottii' },
        '905': { title: 'Fairies', desc1: 'Date: 15/08/2025', desc2: 'Author: Schrottii' },
        '906': { title: 'Net Getout', desc1: 'Date: 21/09/2025', desc2: 'Author: Schrottii' },
        '907': { title: 'Net Ilikemud', desc1: 'Date: 21/09/2025', desc2: 'Author: Schrottii' },
        '908': { title: 'Net Picklerick', desc1: 'Date: 18/07/2025', desc2: 'Author: Schrottii' },
        '909': { title: 'Net Rebicycle', desc1: 'Date: 21/09/2025', desc2: 'Author: Schrottii' },
        '910': { title: 'Slot Machine Emoji Moment', desc1: 'Date: 09/12/2025', desc2: 'Author: Schrottii' },
        '911': { title: 'Shgabbarrel', desc1: 'Date: 15/08/2025', desc2: 'Author: Schrottii' },
        '912': { title: 'Thisbarrelisbtier', desc1: 'Date: 01/07/2024', desc2: 'Author: Schrottii' },
        '913': { title: 'Tuxedovasion', desc1: 'Date: 24/11/2025', desc2: 'Author: Schrottii' }
        '914': { title: 'Real Energy Star', desc1: 'Date: 11/01/2026', desc2: 'Author: Panda' }
    };

    document.querySelectorAll('.barrel-image').forEach(img => {
        img.addEventListener('mouseenter', (e) => {
            const barrelId = img.getAttribute('id');
            const data = barrelData[barrelId];
            if (data) {
                tooltipTitle.textContent = data.title;
                tooltipDesc1.textContent = data.desc1;
                tooltipDesc2.textContent = data.desc2;
                tooltip.style.display = 'block';
                
                const rect = img.getBoundingClientRect();
                tooltip.style.top = `${rect.top + window.scrollY}px`;
                

                const tooltipWidth = tooltip.offsetWidth;
                const rightPosition = rect.right + 10 + tooltipWidth;
                const windowWidth = window.innerWidth;
                
                if (rightPosition > windowWidth) {

                    tooltip.style.left = `${rect.left - tooltipWidth - 10}px`;
                } else {

                    tooltip.style.left = `${rect.right + 10}px`;
                }
            }
        });

        img.addEventListener('mouseleave', () => {
            tooltip.style.display = 'none';
        });
    });
});